### ISSUE TITLE
Error When Starting Game

### ISSUE THREAD

**Issue by alyhasansakr** [alyhasansakr/moonlight-qt#10]
With the current implementation when you start a game by clicking launch the game launches but moonlight gives an assertion error.

**Comment by constantin42** [comment]
I had a similar problem, it crashed my system when I started. I solved it by deactivating the intel graphics driver. perhaps it can also solve your problem

**Comment by alyhasansakr** [comment]
This is an issue known here https://github.com/moonlight-stream/moonlight-common-c/commit/5c9935e11b827d3b8f9a806d14e45d9733acbad0
