### ISSUE TITLE
Add pairing functionality to OK button

### ISSUE THREAD

**Issue by alyhasansakr** [alyhasansakr/moonlight-qt#4]
Implement a silent pairing functionality and add it to the OK button in the new simple dialog

**Comment by alyhasansakr** [comment]
@constantin42 I tried to get the signal and slot thing to work with .ui files, had no luck so far, looks like there is something wrong with how this project is configured, can you try to get a slot working?

**Comment by alyhasansakr** [comment]
I give up on .ui and qml, I will go full C++, check branch [pairing](https://github.com/alyhasansakr/moonlight-qt/tree/pairing)

**Comment by constantin42** [comment]
I pushed an example in the branch "constantin_branch" where I tried a simple UI with a single button. When the button is clicked it will show a message box. I think what you missed was that you need for every ui a class.
Try right click Sources->Add new->Qt->Qt Designer Form Class
Then you can simple when you create a button in UI Right Click->Go to Slot-> it creates automatically the function for the slot


I hope that solves the problem. I will take a look at the branch pairing.

**Comment by constantin42** [comment]
In my branch I actually didn't do that, because I had another dummy project and I simply copied the files from it.

**Comment by alyhasansakr** [comment]
I actually tried creating a class in C++, but I inherited from QDialog instead of QMainWindow (works in other projects but not this one), anyway the definition of signal and slot is not well done in .ui files as it is in C++ files.

Do you see any reason why we shouldn't just write in C++? we are going to do relative layout anyway, so we don't really need a visual editor.

**Comment by constantin42** [comment]
I done that in another project at the beginning because it was more easy, but overtime it become more complicated because I need edto add more more buttons or features, so that it looks "pretty"

**Comment by constantin42** [comment]
Aha, I think the problem was that you need first to have a MainWindowDialog class and then you can add a QDialog class.
I pushed the example in my branch

**Comment by constantin42** [comment]
I need to go to sleep. I am tomorrow free after work, around 17-18, we write/speak again. I setup myself a windows 10 virtualbox machine so that I can test moonlight between computers. You can do that if you follow the follow the ZeroTier from here
https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
But I am still in the progress.

**Comment by alyhasansakr** [comment]
I found the problem, the way the dialog is called is not correct, now it works as expected.

**Comment by alyhasansakr** [comment]
I will continue today to actually add the pairing functionality.

**Comment by alyhasansakr** [comment]
I want you to also try to add the pairing functionality in your branch, this is the main part in this application, lets see how far we both get by the next weekend
