### ISSUE TITLE
Create a dummy server in a virtual box that testing can be done on the same machine

### ISSUE THREAD

**Issue by constantin42** [alyhasansakr/moonlight-qt#8]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by constantin42** [comment]
I will follow the instructions from here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
and try Zerotier

**Comment by alyhasansakr** [comment]
You can just use the same machine on the same operating system.
